name: DOCS

on:
  push:
    branches:
      - main

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - name: Waiting for publishing
        uses: jakejarvis/wait-action@master
        with:
          time: '5m'

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Build docs
        run: |
          yarn install
          cd site
          yarn install
          yarn upgrade yup-schema-faker
          yarn build
          sed -i 's/assets/yup-schema-faker\/assets/' ./dist/index.html
          cd ..
          mv site/dist docs
          git config --global user.email actions@users.noreply.github.com
          git config --global user.name "Action"
          git add docs --force
          git commit -m"docs: update" --no-verify

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: 'docs'
          force: true
